#!/bin/bash

git config --global user.email "rustbochessapp@gmail.com"
git config --global user.name "Rustbot Chessapp"

npm run prettier

git add .

git commit -m "$*"

echo "Press ENTER to push. Ctrl+C to abort."

read input

git push https://pythonideas:$GITHUB_PUSH_TOKEN@github.com/pythonideas/builder main

git push https://rustbotchessapp:$GITLAB_PUSH_TOKEN@gitlab.com/rustbotchessapp/builder main
