#!/bin/bash

git config --global user.email "rustbochessapp@gmail.com"
git config --global user.name "Rustbot Chessapp"

git add .

git commit -m "$*"

git push https://pythonideas:$GITHUB_PUSH_TOKEN@github.com/pythonideas/builder main

git push https://rustbotchessapp:$GITLAB_PUSH_TOKEN@gitlab.com/rustbochessapp/builder main
